#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2025.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Sep 15 22:25:28 EDT 2025
# SW Build 6140274 on Wed May 21 22:58:25 MDT 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot CounterTB_behav xil_defaultlib.CounterTB -log elaborate.log"
xelab --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot CounterTB_behav xil_defaultlib.CounterTB -log elaborate.log

