#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2025.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Oct 29 19:32:53 EDT 2025
# SW Build 6140274 on Wed May 21 22:58:25 MDT 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim test_circuit_TB_behav -key {Behavioral:sim_1:Functional:test_circuit_TB} -tclbatch test_circuit_TB.tcl -log simulate.log"
xsim test_circuit_TB_behav -key {Behavioral:sim_1:Functional:test_circuit_TB} -tclbatch test_circuit_TB.tcl -log simulate.log

